name: Notify IRC
on:
  push:
    branches:
      - master
jobs:
  notify:
    name: Checkout and notify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Notify
        run: |
          set +x e
          git log -1 --pretty="push to master (@%an) %s" | curl "${{ secrets.IRC_NOTIFY_URL }}" -F target=#gonic -F message=@- >/dev/null 2>&1
          exit 0
